"""Private Blob Storage boundary for immutable generated artifacts.

Only references emitted by :func:`build_artifact_reference` are accepted for
deletion.  Callers cannot supply an account, host, arbitrary container, or
arbitrary blob path, which keeps purge operations from becoming an SSRF or
cross-container deletion primitive.
"""

from __future__ import annotations

import hashlib
import os
import re
from dataclasses import dataclass
from urllib.parse import urlsplit


ARTIFACT_CONTAINER = os.getenv("ARCHMORPH_ARTIFACT_CONTAINER", "generated-iac")
_SEGMENT_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
_HASH_RE = re.compile(r"^[0-9a-f]{64}$")
_SCOPE_HASH_RE = re.compile(r"^[0-9a-f]{24}$")


class ArtifactBlobStoreError(RuntimeError):
    """Base error for unavailable or unconfirmed artifact Blob operations."""


class InvalidArtifactBlobReference(ValueError):
    """Raised when a reference is not an app-generated artifact URI."""


@dataclass(frozen=True)
class ArtifactBlobReference:
    uri: str
    container: str
    blob_name: str
    prefix: str


def _scope_hash(value: str) -> str:
    # Pseudonymous scope identifier, not password verification material.
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:24]  # lgtm[py/weak-sensitive-data-hashing]


def _validate_segment(value: str, label: str) -> str:
    if not _SEGMENT_RE.fullmatch(value) or value in {".", ".."}:
        raise InvalidArtifactBlobReference(f"Invalid artifact {label}")
    return value


def build_artifact_reference(
    *,
    owner_user_id: str,
    tenant_id: str,
    analysis_id: str,
    version_id: str,
    artifact_type: str,
    content_hash: str,
) -> ArtifactBlobReference:
    """Build the only Blob reference shape generated by the application."""
    owner_hash = _scope_hash(owner_user_id)
    tenant_hash = _scope_hash(tenant_id)
    _validate_segment(analysis_id, "analysis id")
    _validate_segment(version_id, "version id")
    _validate_segment(artifact_type, "type")
    if not _HASH_RE.fullmatch(content_hash):
        raise InvalidArtifactBlobReference("Invalid artifact content hash")
    prefix = f"artifacts/{tenant_hash}/{owner_hash}/{analysis_id}/{version_id}"
    blob_name = f"{prefix}/{artifact_type}/{content_hash}"
    return ArtifactBlobReference(
        uri=f"azblob://{ARTIFACT_CONTAINER}/{blob_name}",
        container=ARTIFACT_CONTAINER,
        blob_name=blob_name,
        prefix=prefix,
    )


def parse_artifact_reference(
    uri: str,
    *,
    owner_user_id: str,
    tenant_id: str,
) -> ArtifactBlobReference:
    """Validate one internal URI against configured container and caller scope."""
    parsed = urlsplit(uri)
    if (
        parsed.scheme != "azblob"
        or parsed.netloc != ARTIFACT_CONTAINER
        or parsed.query
        or parsed.fragment
        or parsed.username is not None
        or parsed.password is not None
    ):
        raise InvalidArtifactBlobReference("Unapproved artifact Blob reference")
    parts = parsed.path.lstrip("/").split("/")
    if len(parts) != 7 or parts[0] != "artifacts":
        raise InvalidArtifactBlobReference("Unapproved artifact Blob path")
    tenant_hash, owner_hash, analysis_id, version_id, artifact_type, content_hash = parts[1:]
    if not _SCOPE_HASH_RE.fullmatch(tenant_hash) or tenant_hash != _scope_hash(tenant_id):
        raise InvalidArtifactBlobReference("Artifact tenant scope mismatch")
    if not _SCOPE_HASH_RE.fullmatch(owner_hash) or owner_hash != _scope_hash(owner_user_id):
        raise InvalidArtifactBlobReference("Artifact owner scope mismatch")
    _validate_segment(analysis_id, "analysis id")
    _validate_segment(version_id, "version id")
    _validate_segment(artifact_type, "type")
    if not _HASH_RE.fullmatch(content_hash):
        raise InvalidArtifactBlobReference("Invalid artifact content hash")
    blob_name = "/".join(parts)
    return ArtifactBlobReference(
        uri=uri,
        container=ARTIFACT_CONTAINER,
        blob_name=blob_name,
        prefix="/".join(parts[:5]),
    )


def _service_client():
    """Return the configured private Blob client or fail closed."""
    account_url = os.getenv("AZURE_STORAGE_ACCOUNT_URL", "").strip()
    connection_string = os.getenv("AZURE_STORAGE_CONNECTION_STRING", "").strip()
    if not account_url and not connection_string:
        raise ArtifactBlobStoreError("Durable artifact storage is unavailable")
    from azure.storage.blob import BlobServiceClient

    if account_url:
        parsed = urlsplit(account_url)
        if (
            parsed.scheme != "https"
            or not parsed.hostname
            or parsed.username is not None
            or parsed.password is not None
            or parsed.path not in {"", "/"}
            or parsed.query
            or parsed.fragment
        ):
            raise ArtifactBlobStoreError("Artifact storage account URL is invalid")
        from azure.identity import DefaultAzureCredential

        return BlobServiceClient(account_url.rstrip("/"), credential=DefaultAzureCredential())
    return BlobServiceClient.from_connection_string(connection_string)


def upload_artifact_blob(reference: ArtifactBlobReference, content: bytes) -> None:
    """Upload immutable bytes to the approved private container."""
    blob = _service_client().get_blob_client(
        container=reference.container,
        blob=reference.blob_name,
    )
    blob.upload_blob(
        content,
        overwrite=False,
        metadata={"sha256": reference.blob_name.rsplit("/", 1)[-1]},
    )


def artifact_blob_absent(
    uri: str,
    *,
    owner_user_id: str,
    tenant_id: str,
) -> bool:
    """Confirm absence; an unavailable store is not treated as deletion."""
    reference = parse_artifact_reference(
        uri,
        owner_user_id=owner_user_id,
        tenant_id=tenant_id,
    )
    blob = _service_client().get_blob_client(
        container=reference.container,
        blob=reference.blob_name,
    )
    try:
        return not bool(blob.exists())
    except Exception as exc:
        raise ArtifactBlobStoreError("Artifact Blob absence could not be confirmed") from exc


def delete_artifact_blob(
    uri: str,
    *,
    owner_user_id: str,
    tenant_id: str,
) -> bool:
    """Delete one approved Blob and verify absence; not-found is idempotent."""
    reference = parse_artifact_reference(
        uri,
        owner_user_id=owner_user_id,
        tenant_id=tenant_id,
    )
    blob = _service_client().get_blob_client(
        container=reference.container,
        blob=reference.blob_name,
    )
    deleted = True
    try:
        blob.delete_blob()
    except Exception as exc:
        try:
            from azure.core.exceptions import ResourceNotFoundError
        except ImportError:  # pragma: no cover - azure SDK is a runtime dependency
            ResourceNotFoundError = ()  # type: ignore[assignment]
        if not isinstance(exc, ResourceNotFoundError):
            raise ArtifactBlobStoreError("Artifact Blob deletion failed") from exc
        deleted = False
    try:
        if blob.exists():
            raise ArtifactBlobStoreError("Artifact Blob deletion was not confirmed")
    except ArtifactBlobStoreError:
        raise
    except Exception as exc:
        raise ArtifactBlobStoreError("Artifact Blob absence could not be confirmed") from exc
    return deleted