"""Immutable generated-export persistence bound to canonical analysis versions."""

from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass
from typing import Any

from error_envelope import ArchmorphException
from prompt_guard import sanitize_response
from routers.shared import get_request_durable_principal, has_canonical_durable_principal

_ARTIFACT_CONTAINER = os.getenv("ARCHMORPH_ARTIFACT_CONTAINER", "generated-iac")
_INLINE_TEXT_LIMIT = int(os.getenv("ARCHMORPH_ARTIFACT_INLINE_TEXT_LIMIT", "1048576"))


@dataclass(frozen=True)
class ExportArtifactRef:
    id: str
    version_id: str
    content_hash: str
    size_bytes: int


def _redact_text_payload(content: bytes) -> bytes:
    """Fail closed if persistence would alter secret-bearing generated bytes."""
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        return content
    redacted = sanitize_response(text)
    if redacted != text:
        raise ArchmorphException(
            422,
            "Generated export contains secret-like material and was not persisted.",
            details={"error": "artifact_secret_detected"},
        )
    return content


def _upload_blob(
    *,
    owner_user_id: str,
    tenant_id: str,
    analysis_id: str,
    version_id: str,
    artifact_type: str,
    content_hash: str,
    content: bytes,
) -> str:
    """Upload immutable bytes to private Blob Storage and return an internal URI."""
    account_url = os.getenv("AZURE_STORAGE_ACCOUNT_URL", "")
    connection_string = os.getenv("AZURE_STORAGE_CONNECTION_STRING", "")
    if not account_url and not connection_string:
        raise ArchmorphException(
            503,
            "Durable artifact storage is unavailable.",
            details={"error": "artifact_storage_unavailable"},
            headers={"Retry-After": "30"},
        )
    from azure.storage.blob import BlobServiceClient

    if account_url:
        from azure.identity import DefaultAzureCredential

        service = BlobServiceClient(account_url, credential=DefaultAzureCredential())
    else:
        service = BlobServiceClient.from_connection_string(connection_string)
    owner_hash = hashlib.sha256(owner_user_id.encode("utf-8")).hexdigest()[:24]
    tenant_hash = hashlib.sha256(tenant_id.encode("utf-8")).hexdigest()[:24]
    blob_name = (
        f"artifacts/{tenant_hash}/{owner_hash}/{analysis_id}/{version_id}/"
        f"{artifact_type}/{content_hash}"
    )
    blob = service.get_blob_client(container=_ARTIFACT_CONTAINER, blob=blob_name)
    blob.upload_blob(content, overwrite=False, metadata={"sha256": content_hash})
    return f"azblob://{_ARTIFACT_CONTAINER}/{blob_name}"


def persist_generated_export(
    request: Any,
    *,
    diagram_id: str,
    artifact_type: str,
    format: str,
    content: bytes | str,
    force_blob: bool = False,
):
    """Persist exact generated bytes against the locked current immutable version."""
    principal = get_request_durable_principal(request)
    if (
        principal is None
        or not principal.get("tenant_id")
        or not has_canonical_durable_principal(request)
    ):
        from routers.shared import SESSION_STORE

        session = SESSION_STORE.peek(diagram_id)
        production_like = os.getenv("ENVIRONMENT", "development").lower() in {
            "production",
            "prod",
            "staging",
        }
        public_compatibility = bool(
            isinstance(session, dict)
            and (
                session.get("is_sample")
                or session.get("is_template")
                or session.get("is_starter")
                or (
                    not production_like
                    and (
                        not session.get("_owner_user_id")
                        or not has_canonical_durable_principal(request)
                    )
                )
            )
        )
        if public_compatibility:
            return None
        raise ArchmorphException(
            409,
            "Canonical analysis version is required for export.",
            details={"error": "canonical_version_required"},
        )
    payload = content.encode("utf-8") if isinstance(content, str) else bytes(content)
    _redact_text_payload(payload)

    from database import SessionLocal
    from workspace_store import create_export_artifact, get_current_analysis_version

    db = SessionLocal()
    try:
        analysis, version = get_current_analysis_version(
            db,
            diagram_id=diagram_id,
            owner_user_id=principal["owner_user_id"],
            tenant_id=principal["tenant_id"],
        )
        is_utf8 = True
        try:
            payload.decode("utf-8")
        except UnicodeDecodeError:
            is_utf8 = False
        storage_url = None
        if force_blob or not is_utf8 or len(payload) > _INLINE_TEXT_LIMIT:
            content_hash = hashlib.sha256(payload).hexdigest()
            try:
                storage_url = _upload_blob(
                    owner_user_id=principal["owner_user_id"],
                    tenant_id=principal["tenant_id"],
                    analysis_id=analysis.id,
                    version_id=version.id,
                    artifact_type=artifact_type,
                    content_hash=content_hash,
                    content=payload,
                )
            except Exception as exc:
                # A retry may race an already-completed immutable upload.
                if type(exc).__name__ not in {"ResourceExistsError"}:
                    raise
                storage_url = (
                    f"azblob://{_ARTIFACT_CONTAINER}/artifacts/"
                    f"{hashlib.sha256(principal['tenant_id'].encode()).hexdigest()[:24]}/"
                    f"{hashlib.sha256(principal['owner_user_id'].encode()).hexdigest()[:24]}/"
                    f"{analysis.id}/{version.id}/{artifact_type}/{content_hash}"
                )
        artifact = create_export_artifact(
            db,
            diagram_id=diagram_id,
            owner_user_id=principal["owner_user_id"],
            tenant_id=principal["tenant_id"],
            artifact_type=artifact_type,
            format=format,
            content=payload,
            storage_url=storage_url,
            inline_content=(payload.decode("utf-8") if storage_url is None else None),
        )
        return ExportArtifactRef(
            id=artifact.id,
            version_id=artifact.version_id,
            content_hash=artifact.content_hash,
            size_bytes=artifact.size_bytes,
        )
    except ValueError as exc:
        raise ArchmorphException(
            409,
            "Canonical analysis version is required for export.",
            details={"error": "canonical_version_required"},
        ) from exc
    finally:
        db.close()


async def persist_generated_export_async(request: Any, **kwargs):
    """Threadpool wrapper that preserves request context and exceptions."""
    from functools import partial
    from starlette.concurrency import run_in_threadpool

    return await run_in_threadpool(partial(persist_generated_export, request, **kwargs))
