"""Immutable generated-export persistence bound to canonical analysis versions."""

from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass
from typing import Any

from error_envelope import ArchmorphException
from artifact_blob_store import (
    ArtifactBlobStoreError,
    build_artifact_reference,
    delete_artifact_blob,
    upload_artifact_blob,
)
from export_content_scanner import scan_generated_export
from routers.shared import get_request_durable_principal, has_canonical_durable_principal

_INLINE_TEXT_LIMIT = int(os.getenv("ARCHMORPH_ARTIFACT_INLINE_TEXT_LIMIT", "1048576"))


@dataclass(frozen=True)
class ExportArtifactRef:
    id: str
    version_id: str
    content_hash: str
    size_bytes: int


def _is_public_compatibility_session(
    diagram_id: str,
    *,
    canonical_principal: bool,
) -> bool:
    """Return whether an export belongs to non-customer canonical state."""
    from routers.shared import SESSION_STORE

    session = SESSION_STORE.peek(diagram_id)
    if not isinstance(session, dict):
        return False
    if session.get("is_sample") and diagram_id.startswith("sample-"):
        return True
    if session.get("is_template") or session.get("is_starter"):
        return True
    production_like = os.getenv("ENVIRONMENT", "development").lower() in {
        "production",
        "prod",
        "staging",
    }
    return bool(
        not production_like
        and (
            not session.get("_owner_user_id")
            or not canonical_principal
        )
    )


def _upload_blob(
    *,
    owner_user_id: str,
    tenant_id: str,
    analysis_id: str,
    version_id: str,
    artifact_type: str,
    content_hash: str,
    content: bytes,
) -> str:
    """Upload immutable bytes to private Blob Storage and return an internal URI."""
    reference = build_artifact_reference(
        owner_user_id=owner_user_id,
        tenant_id=tenant_id,
        analysis_id=analysis_id,
        version_id=version_id,
        artifact_type=artifact_type,
        content_hash=content_hash,
    )
    try:
        upload_artifact_blob(reference, content)
    except ArtifactBlobStoreError as exc:
        raise ArchmorphException(
            503,
            "Durable artifact storage is unavailable.",
            details={"error": "artifact_storage_unavailable"},
            headers={"Retry-After": "30"},
        ) from exc
    return reference.uri


def persist_generated_export(
    request: Any,
    *,
    diagram_id: str,
    artifact_type: str,
    format: str,
    content: bytes | str,
    force_blob: bool = False,
):
    """Persist exact generated bytes against the locked current immutable version."""
    principal = get_request_durable_principal(request)
    if (
        principal is None
        or not principal.get("tenant_id")
        or not has_canonical_durable_principal(request)
    ):
        if _is_public_compatibility_session(
            diagram_id,
            canonical_principal=False,
        ):
            return None
        raise ArchmorphException(
            409,
            "Canonical analysis version is required for export.",
            details={"error": "canonical_version_required"},
        )
    payload = content.encode("utf-8") if isinstance(content, str) else bytes(content)
    scan_generated_export(payload, format=format)

    from database import SessionLocal
    from workspace_store import (
        CanonicalWriteDeniedError,
        create_export_artifact,
        find_export_artifact,
        get_current_analysis_version,
    )

    db = SessionLocal()
    try:
        analysis, version = get_current_analysis_version(
            db,
            diagram_id=diagram_id,
            owner_user_id=principal["owner_user_id"],
            tenant_id=principal["tenant_id"],
        )
        content_hash = hashlib.sha256(payload).hexdigest()
        existing = find_export_artifact(
            db,
            analysis_id=analysis.id,
            version_id=version.id,
            owner_user_id=principal["owner_user_id"],
            tenant_id=principal["tenant_id"],
            artifact_type=artifact_type,
            content_hash=content_hash,
        )
        if existing is not None:
            return ExportArtifactRef(
                id=existing.id,
                version_id=existing.version_id,
                content_hash=existing.content_hash,
                size_bytes=existing.size_bytes,
            )
        is_utf8 = True
        try:
            payload.decode("utf-8")
        except UnicodeDecodeError:
            is_utf8 = False
        storage_url = None
        uploaded_new_blob = False
        if force_blob or not is_utf8 or len(payload) > _INLINE_TEXT_LIMIT:
            reference = build_artifact_reference(
                owner_user_id=principal["owner_user_id"],
                tenant_id=principal["tenant_id"],
                analysis_id=analysis.id,
                version_id=version.id,
                artifact_type=artifact_type,
                content_hash=content_hash,
            )
            try:
                storage_url = _upload_blob(
                    owner_user_id=principal["owner_user_id"],
                    tenant_id=principal["tenant_id"],
                    analysis_id=analysis.id,
                    version_id=version.id,
                    artifact_type=artifact_type,
                    content_hash=content_hash,
                    content=payload,
                )
                uploaded_new_blob = True
            except Exception as exc:
                # A retry may race an already-completed immutable upload.
                if type(exc).__name__ not in {"ResourceExistsError"}:
                    raise
                storage_url = reference.uri
        try:
            artifact = create_export_artifact(
                db,
                diagram_id=diagram_id,
                owner_user_id=principal["owner_user_id"],
                tenant_id=principal["tenant_id"],
                artifact_type=artifact_type,
                format=format,
                content=payload,
                storage_url=storage_url,
                inline_content=(payload.decode("utf-8") if storage_url is None else None),
            )
        except Exception:
            if uploaded_new_blob and storage_url:
                try:
                    delete_artifact_blob(
                        storage_url,
                        owner_user_id=principal["owner_user_id"],
                        tenant_id=principal["tenant_id"],
                    )
                except Exception as cleanup_exc:
                    raise ArchmorphException(
                        503,
                        "Artifact persistence failed and uploaded bytes could not be cleaned up.",
                        details={"error": "artifact_persistence_cleanup_pending"},
                        headers={"Retry-After": "30"},
                    ) from cleanup_exc
            raise
        return ExportArtifactRef(
            id=artifact.id,
            version_id=artifact.version_id,
            content_hash=artifact.content_hash,
            size_bytes=artifact.size_bytes,
        )
    except CanonicalWriteDeniedError as exc:
        raise ArchmorphException(404, "Diagram not found") from exc
    except ValueError as exc:
        # Public samples/templates intentionally have no customer-owned
        # canonical analysis version, even when viewed with an API key. Their
        # bytes are returned but do not enter customer artifact retention.
        if _is_public_compatibility_session(
            diagram_id,
            canonical_principal=True,
        ):
            return None
        raise ArchmorphException(
            409,
            "Canonical analysis version is required for export.",
            details={"error": "canonical_version_required"},
        ) from exc
    finally:
        db.close()


async def persist_generated_export_async(request: Any, **kwargs):
    """Threadpool wrapper that preserves request context and exceptions."""
    from functools import partial
    from starlette.concurrency import run_in_threadpool

    return await run_in_threadpool(partial(persist_generated_export, request, **kwargs))
