"""
Archmorph HLD Export — Generate Word, PDF, and PowerPoint documents from HLD data.

Supports exporting with or without architecture diagrams.
Uses python-docx for Word, fpdf2 for PDF, and python-pptx for PowerPoint.
"""

import base64
import io
import logging
from typing import Any, Dict, List, Optional

from version import __version__

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────
# Color palette (matching Archmorph UI theme)
# ─────────────────────────────────────────────────────────────
BRAND_GREEN = (34, 197, 94)       # #22C55E — CTA green
BRAND_DARK = (15, 23, 42)         # #0F172A — primary dark
BRAND_SURFACE = (2, 6, 23)        # #020617 — surface
HEADING_BLUE = (59, 130, 246)     # #3B82F6 — info blue
WHITE = (255, 255, 255)
LIGHT_GRAY = (226, 232, 240)      # #E2E8F0
DARK_GRAY = (100, 116, 139)       # #64748B


# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────
def _safe(val: Any, default: str = "N/A") -> str:
    """Safely convert a value to string."""
    if val is None:
        return default
    return str(val)


def _pdf_safe(text: str) -> str:
    """Sanitize text for PDF rendering with built-in Helvetica (latin-1 only).

    Replaces common Unicode characters with ASCII equivalents so fpdf2
    can render them without requiring a TrueType Unicode font.
    """
    replacements = {
        "\u2014": "--",   # em-dash
        "\u2013": "-",    # en-dash
        "\u2018": "'",    # left single quote
        "\u2019": "'",    # right single quote
        "\u201c": '"',    # left double quote
        "\u201d": '"',    # right double quote
        "\u2026": "...",  # ellipsis
        "\u2022": "-",    # bullet
        "\u2192": "->",   # right arrow
        "\u2190": "<-",   # left arrow
        "\u00a0": " ",    # non-breaking space
        "\u00b7": "-",    # middle dot
        "\u2502": "|",    # box drawing vertical
        "\u251c": "|",    # box drawing tee
        "\u2500": "-",    # box drawing horizontal
        "\u2514": "`",    # box drawing corner
        "\u25b6": ">",    # right-pointing triangle
    }
    for char, repl in replacements.items():
        text = text.replace(char, repl)
    # Strip any remaining non-latin-1 characters
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _decode_diagram_image(diagram_b64: Optional[str]) -> Optional[bytes]:
    """Decode a base64-encoded diagram image, if provided."""
    if not diagram_b64:
        return None
    try:
        # Strip data URI prefix if present
        if "," in diagram_b64:
            diagram_b64 = diagram_b64.split(",", 1)[1]
        return base64.b64decode(diagram_b64)
    except Exception:
        logger.warning("Failed to decode diagram image")
        return None


# ═════════════════════════════════════════════════════════════
# WORD (DOCX) EXPORT
# ═════════════════════════════════════════════════════════════
def export_hld_docx(hld: Dict[str, Any], include_diagrams: bool = True,
                    diagram_b64: Optional[str] = None) -> bytes:
    """Export HLD to a Word (.docx) document. Returns bytes."""
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT

    doc = Document()

    # ── Page style ──
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)
    font.color.rgb = RGBColor(51, 65, 85)

    for level in range(1, 4):
        hs = doc.styles[f"Heading {level}"]
        hs.font.color.rgb = RGBColor(*BRAND_DARK)
        hs.font.name = "Calibri"

    # ── Title page ──
    title = doc.add_heading(hld.get("title", "High-Level Design Document"), level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.runs[0]
    run.font.size = Pt(28)
    run.font.color.rgb = RGBColor(*BRAND_GREEN)

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = sub.add_run("Generated by Archmorph — AI-powered Cloud Architecture Translator")
    sub_run.font.size = Pt(11)
    sub_run.font.color.rgb = RGBColor(*DARK_GRAY)
    sub_run.font.italic = True

    # Metadata
    meta = hld.get("_metadata") or {}
    if meta:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        info_parts = []
        if meta.get("source_provider"):
            info_parts.append(f"Source: {meta['source_provider'].upper()}")
        if meta.get("services_count"):
            info_parts.append(f"{meta['services_count']} services")
        if meta.get("zones_count"):
            info_parts.append(f"{meta['zones_count']} zones")
        r = p.add_run(" | ".join(info_parts))
        r.font.size = Pt(10)
        r.font.color.rgb = RGBColor(*DARK_GRAY)

    doc.add_page_break()

    # ─── Helper to add styled section ───
    def add_section(heading: str, level: int = 1):
        h = doc.add_heading(heading, level=level)
        return h

    def add_kv(key: str, value: str):
        p = doc.add_paragraph()
        kr = p.add_run(f"{key}: ")
        kr.bold = True
        kr.font.size = Pt(11)
        p.add_run(_safe(value))

    def add_bullet_list(items: List[str]):
        for item in items:
            doc.add_paragraph(_safe(item), style="List Bullet")

    # ── 1. Executive Summary ──
    add_section("1. Executive Summary")
    doc.add_paragraph(_safe(hld.get("executive_summary")))

    # ── 2. Architecture Overview ──
    arch = hld.get("architecture_overview") or {}
    add_section("2. Architecture Overview")
    add_kv("Architecture Style", arch.get("architecture_style"))
    add_kv("Deployment Model", arch.get("deployment_model"))
    if arch.get("description"):
        doc.add_paragraph(arch["description"])
    if arch.get("diagram_description"):
        add_section("Data Flow", level=2)
        doc.add_paragraph(arch["diagram_description"])

    # Insert architecture diagram if provided
    if include_diagrams and diagram_b64:
        img_bytes = _decode_diagram_image(diagram_b64)
        if img_bytes:
            add_section("Architecture Diagram", level=2)
            stream = io.BytesIO(img_bytes)
            doc.add_picture(stream, width=Inches(6))
            last_para = doc.paragraphs[-1]
            last_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # ── 3. Services ──
    services = hld.get("services", [])
    if services:
        add_section("3. Azure Services — Detailed Design")
        for i, svc in enumerate(services, 1):
            add_section(f"3.{i}. {_safe(svc.get('azure_service'))}", level=2)
            if svc.get("source_service"):
                add_kv("Replaces", svc["source_service"])
            if svc.get("description"):
                doc.add_paragraph(svc["description"])
            add_kv("Justification", svc.get("justification"))
            if svc.get("alternatives_considered"):
                add_kv("Alternatives Considered", ", ".join(svc["alternatives_considered"]))
            add_kv("Recommended Tier", svc.get("tier_recommendation"))
            add_kv("SLA", svc.get("sla"))
            add_kv("Estimated Cost", svc.get("estimated_monthly_cost"))

            comm = svc.get("communication", {})
            if comm.get("connects_to"):
                add_kv("Connects To", f"{', '.join(comm['connects_to'])} ({_safe(comm.get('protocol'))} — {_safe(comm.get('pattern'))})")

            if svc.get("limitations"):
                p = doc.add_paragraph()
                p.add_run("Limitations:").bold = True
                add_bullet_list(svc["limitations"])

    # ── 4. Networking ──
    net = hld.get("networking_design") or {}
    if net:
        add_section("4. Networking Design")
        for field, label in [("topology", "Topology"), ("vnet_design", "VNet Design"),
                             ("connectivity", "Connectivity"), ("dns_strategy", "DNS Strategy")]:
            if net.get(field):
                add_kv(label, net[field])
        if net.get("security_controls"):
            add_kv("Security Controls", ", ".join(net["security_controls"]))
        if net.get("recommendations"):
            p = doc.add_paragraph()
            p.add_run("Recommendations:").bold = True
            add_bullet_list(net["recommendations"])

    # ── 5. Security ──
    sec = hld.get("security_design") or {}
    if sec:
        add_section("5. Security Design")
        for field, label in [("identity", "Identity & Access"), ("data_protection", "Data Protection"),
                             ("network_security", "Network Security"), ("secrets_management", "Secrets Management")]:
            if sec.get(field):
                add_kv(label, sec[field])
        if sec.get("compliance_frameworks"):
            add_kv("Compliance Frameworks", ", ".join(sec["compliance_frameworks"]))

    # ── 6. Data Architecture ──
    data = hld.get("data_architecture") or {}
    if data:
        add_section("6. Data Architecture")
        for field, label in [("data_flow", "Data Flow"), ("storage_strategy", "Storage Strategy"),
                             ("database_strategy", "Database Strategy"), ("data_residency", "Data Residency"),
                             ("backup_and_recovery", "Backup & Recovery")]:
            if data.get(field):
                add_kv(label, data[field])

    # ── 7. CAF Alignment ──
    caf = hld.get("azure_caf_alignment") or {}
    if caf:
        add_section("7. Azure Cloud Adoption Framework Alignment")
        for field, label in [("landing_zone", "Landing Zone"), ("management_groups", "Management Groups"),
                             ("subscription_design", "Subscription Design"), ("naming_convention", "Naming Convention"),
                             ("tagging_strategy", "Tagging Strategy"), ("resource_organization", "Resource Organization")]:
            if caf.get(field):
                add_kv(label, caf[field])

    # ── 8. FinOps ──
    fin = hld.get("finops") or {}
    if fin:
        add_section("8. FinOps — Cost Management")
        add_kv("Total Estimated Monthly Cost", fin.get("total_estimated_monthly_cost"))
        if fin.get("cost_optimization_recommendations"):
            p = doc.add_paragraph()
            p.add_run("Cost Optimization Recommendations:").bold = True
            add_bullet_list(fin["cost_optimization_recommendations"])
        if fin.get("reserved_instances_candidates"):
            add_kv("Reserved Instance Candidates", ", ".join(fin["reserved_instances_candidates"]))
        if fin.get("cost_monitoring"):
            add_kv("Cost Monitoring", fin["cost_monitoring"])

    # ── 9. Region Strategy ──
    region = hld.get("region_strategy") or {}
    if region:
        add_section("9. Region Strategy")
        add_kv("Primary Region", region.get("primary_region"))
        add_kv("DR Region", region.get("dr_region"))
        if region.get("region_selection_factors"):
            add_kv("Selection Factors", ", ".join(region["region_selection_factors"]))
        if region.get("data_residency_considerations"):
            add_kv("Data Residency", region["data_residency_considerations"])

    # ── 10. WAF Assessment ──
    waf = hld.get("waf_assessment") or {}
    if waf:
        add_section("10. Well-Architected Framework Assessment")
        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 1"
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        hdr = table.rows[0].cells
        hdr[0].text = "Pillar"
        hdr[1].text = "Score"
        hdr[2].text = "Notes"
        for pillar in ["reliability", "security", "cost_optimization", "operational_excellence", "performance_efficiency"]:
            p = waf.get(pillar, {})
            row = table.add_row().cells
            row[0].text = pillar.replace("_", " ").title()
            row[1].text = _safe(p.get("score"))
            row[2].text = _safe(p.get("notes"), "")

    # ── 11. Migration Roadmap ──
    mig = hld.get("migration_approach") or {}
    if mig:
        add_section("11. Migration Roadmap")
        add_kv("Strategy", mig.get("strategy"))
        for phase in mig.get("phases", []):
            add_section(f"Phase {phase.get('phase', '?')}: {_safe(phase.get('name'))}", level=2)
            if phase.get("description"):
                doc.add_paragraph(phase["description"])
            if phase.get("services"):
                add_kv("Services", ", ".join(phase["services"]))
            add_kv("Duration", f"{phase.get('duration_weeks', '?')} weeks")
            if phase.get("risks"):
                add_kv("Risks", ", ".join(phase["risks"]))
        if mig.get("rollback_plan"):
            add_kv("Rollback Plan", mig["rollback_plan"])
        if mig.get("testing_strategy"):
            add_kv("Testing Strategy", mig["testing_strategy"])

    # ── 12. Considerations ──
    considerations = hld.get("considerations", [])
    if considerations:
        add_section("12. Key Considerations")
        add_bullet_list(considerations)

    # ── 13. Risks & Mitigations ──
    risks = hld.get("risks_and_mitigations", [])
    if risks:
        add_section("13. Risks & Mitigations")
        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 1"
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        hdr = table.rows[0].cells
        hdr[0].text = "Risk"
        hdr[1].text = "Impact"
        hdr[2].text = "Mitigation"
        for r in risks:
            row = table.add_row().cells
            row[0].text = _safe(r.get("risk"), "")
            row[1].text = _safe(r.get("impact"), "")
            row[2].text = _safe(r.get("mitigation"), "")

    # ── 14. Next Steps ──
    next_steps = hld.get("next_steps", [])
    if next_steps:
        add_section("14. Next Steps")
        for i, s in enumerate(next_steps, 1):
            doc.add_paragraph(f"{i}. {s}")

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = footer.add_run(f"Generated by Archmorph v{__version__}")
    r.font.size = Pt(9)
    r.font.color.rgb = RGBColor(*DARK_GRAY)
    r.font.italic = True

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ═════════════════════════════════════════════════════════════
# PDF EXPORT
# ═════════════════════════════════════════════════════════════
def export_hld_pdf(hld: Dict[str, Any], include_diagrams: bool = True,
                   diagram_b64: Optional[str] = None) -> bytes:
    """Export HLD to a PDF document. Returns bytes."""
    from fpdf import FPDF

    class ArchmorphPDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(*DARK_GRAY)
            self.cell(0, 6, _pdf_safe(hld.get("title", "Archmorph HLD")), align="L")
            self.ln(8)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(*DARK_GRAY)
            self.cell(0, 10, _pdf_safe(f"Page {self.page_no()}/{{nb}} -- Generated by Archmorph v{__version__}"), align="C")

        def section_heading(self, text: str, level: int = 1):
            sizes = {1: 16, 2: 13, 3: 11}
            self.set_font("Helvetica", "B", sizes.get(level, 11))
            self.set_text_color(*BRAND_DARK)
            self.ln(4)
            self.multi_cell(0, 7, _pdf_safe(text))
            self.ln(2)

        def body_text(self, text: str):
            self.set_font("Helvetica", "", 10)
            self.set_text_color(51, 65, 85)
            self.multi_cell(0, 5, _pdf_safe(text))
            self.ln(1)

        def key_value(self, key: str, value: str):
            key = _pdf_safe(key)
            value = _pdf_safe(value)
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(*BRAND_DARK)
            w = self.get_string_width(f"{key}: ") + 2
            self.cell(w, 5, f"{key}: ")
            self.set_font("Helvetica", "", 10)
            self.set_text_color(51, 65, 85)
            self.multi_cell(0, 5, value)
            self.ln(1)

        def bullet_list(self, items: List[str]):
            self.set_font("Helvetica", "", 10)
            self.set_text_color(51, 65, 85)
            for item in items:
                self.multi_cell(0, 5, _pdf_safe(f"  - {item}"))
                self.ln(0.5)

    pdf = ArchmorphPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title page ──
    pdf.ln(40)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*BRAND_GREEN)
    pdf.multi_cell(0, 12, _pdf_safe(hld.get("title", "High-Level Design Document")), align="C")
    pdf.ln(6)

    pdf.set_font("Helvetica", "I", 12)
    pdf.set_text_color(*DARK_GRAY)
    pdf.cell(0, 8, "Generated by Archmorph", align="C")
    pdf.ln(8)
    pdf.cell(0, 6, "AI-powered Cloud Architecture Translator", align="C")
    pdf.ln(20)

    meta = hld.get("_metadata") or {}
    if meta:
        info_parts = []
        if meta.get("source_provider"):
            info_parts.append(f"Source: {meta['source_provider'].upper()}")
        if meta.get("services_count"):
            info_parts.append(f"{meta['services_count']} services")
        if meta.get("zones_count"):
            info_parts.append(f"{meta['zones_count']} zones")
        if info_parts:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*DARK_GRAY)
            pdf.cell(0, 6, " | ".join(info_parts), align="C")

    pdf.add_page()

    # ── 1. Executive Summary ──
    pdf.section_heading("1. Executive Summary")
    pdf.body_text(_safe(hld.get("executive_summary")))

    # ── 2. Architecture Overview ──
    arch = hld.get("architecture_overview") or {}
    pdf.section_heading("2. Architecture Overview")
    pdf.key_value("Architecture Style", _safe(arch.get("architecture_style")))
    pdf.key_value("Deployment Model", _safe(arch.get("deployment_model")))
    if arch.get("description"):
        pdf.body_text(arch["description"])

    if include_diagrams and diagram_b64:
        img_bytes = _decode_diagram_image(diagram_b64)
        if img_bytes:
            pdf.section_heading("Architecture Diagram", level=2)
            img_stream = io.BytesIO(img_bytes)
            # Try to get image dimensions — fit to page width
            try:
                pdf.image(img_stream, x=15, w=180)
            except Exception:
                pdf.body_text("[Diagram image could not be embedded]")
            pdf.ln(5)

    # ── 3. Services ──
    services = hld.get("services", [])
    if services:
        pdf.section_heading("3. Azure Services — Detailed Design")
        for i, svc in enumerate(services, 1):
            pdf.section_heading(f"3.{i}. {_safe(svc.get('azure_service'))}", level=2)
            if svc.get("source_service"):
                pdf.key_value("Replaces", svc["source_service"])
            if svc.get("description"):
                pdf.body_text(svc["description"])
            pdf.key_value("Justification", _safe(svc.get("justification")))
            pdf.key_value("Tier", _safe(svc.get("tier_recommendation")))
            pdf.key_value("SLA", _safe(svc.get("sla")))
            pdf.key_value("Est. Cost", _safe(svc.get("estimated_monthly_cost")))

    # ── 4. Networking ──
    net = hld.get("networking_design") or {}
    if net:
        pdf.section_heading("4. Networking Design")
        for field, label in [("topology", "Topology"), ("vnet_design", "VNet Design"),
                             ("dns_strategy", "DNS Strategy")]:
            if net.get(field):
                pdf.key_value(label, net[field])
        if net.get("security_controls"):
            pdf.key_value("Security Controls", ", ".join(net["security_controls"]))

    # ── 5. Security ──
    sec = hld.get("security_design") or {}
    if sec:
        pdf.section_heading("5. Security Design")
        for field, label in [("identity", "Identity & Access"), ("data_protection", "Data Protection"),
                             ("network_security", "Network Security"), ("secrets_management", "Secrets")]:
            if sec.get(field):
                pdf.key_value(label, sec[field])

    # ── 6. Data Architecture ──
    data = hld.get("data_architecture") or {}
    if data:
        pdf.section_heading("6. Data Architecture")
        for field, label in [("data_flow", "Data Flow"), ("storage_strategy", "Storage"),
                             ("database_strategy", "Database"), ("backup_and_recovery", "Backup & Recovery")]:
            if data.get(field):
                pdf.key_value(label, data[field])

    # ── 7. CAF Alignment ──
    caf = hld.get("azure_caf_alignment") or {}
    if caf:
        pdf.section_heading("7. Azure CAF Alignment")
        for field, label in [("landing_zone", "Landing Zone"), ("naming_convention", "Naming"),
                             ("tagging_strategy", "Tagging"), ("subscription_design", "Subscription")]:
            if caf.get(field):
                pdf.key_value(label, caf[field])

    # ── 8. FinOps ──
    fin = hld.get("finops") or {}
    if fin:
        pdf.section_heading("8. FinOps — Cost Management")
        pdf.key_value("Total Monthly Cost", _safe(fin.get("total_estimated_monthly_cost")))
        if fin.get("cost_optimization_recommendations"):
            pdf.body_text("Cost Optimization:")
            pdf.bullet_list(fin["cost_optimization_recommendations"])

    # ── 9. Region Strategy ──
    region = hld.get("region_strategy") or {}
    if region:
        pdf.section_heading("9. Region Strategy")
        pdf.key_value("Primary Region", _safe(region.get("primary_region")))
        pdf.key_value("DR Region", _safe(region.get("dr_region")))

    # ── 10. WAF Assessment ──
    waf = hld.get("waf_assessment") or {}
    if waf:
        pdf.section_heading("10. Well-Architected Framework Assessment")
        # Simple table
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_fill_color(*LIGHT_GRAY)
        pdf.cell(55, 7, "Pillar", 1, fill=True)
        pdf.cell(25, 7, "Score", 1, fill=True)
        pdf.cell(0, 7, "Notes", 1, fill=True)
        pdf.ln()
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)
        for pillar in ["reliability", "security", "cost_optimization", "operational_excellence", "performance_efficiency"]:
            p = waf.get(pillar, {})
            pdf.cell(55, 6, pillar.replace("_", " ").title(), 1)
            pdf.cell(25, 6, _safe(p.get("score")), 1)
            pdf.cell(0, 6, _safe(p.get("notes"), "")[:60], 1)
            pdf.ln()

    # ── 11. Migration ──
    mig = hld.get("migration_approach") or {}
    if mig:
        pdf.section_heading("11. Migration Roadmap")
        pdf.key_value("Strategy", _safe(mig.get("strategy")))
        for phase in mig.get("phases", []):
            pdf.section_heading(f"Phase {phase.get('phase', '?')}: {_safe(phase.get('name'))}", level=2)
            if phase.get("description"):
                pdf.body_text(phase["description"])
            if phase.get("services"):
                pdf.key_value("Services", ", ".join(phase["services"]))
            pdf.key_value("Duration", f"{phase.get('duration_weeks', '?')} weeks")

    # ── 12-14. Considerations, Risks, Next Steps ──
    considerations = hld.get("considerations", [])
    if considerations:
        pdf.section_heading("12. Key Considerations")
        pdf.bullet_list(considerations)

    risks = hld.get("risks_and_mitigations", [])
    if risks:
        pdf.section_heading("13. Risks & Mitigations")
        for r in risks:
            pdf.key_value(_safe(r.get("risk"), "Risk"), f"Impact: {_safe(r.get('impact'), '-')} | Mitigation: {_safe(r.get('mitigation'), '-')}")

    next_steps = hld.get("next_steps", [])
    if next_steps:
        pdf.section_heading("14. Next Steps")
        for i, s in enumerate(next_steps, 1):
            pdf.body_text(f"{i}. {s}")

    return bytes(pdf.output())


# ═════════════════════════════════════════════════════════════
# POWERPOINT (PPTX) EXPORT
# ═════════════════════════════════════════════════════════════
def export_hld_pptx(hld: Dict[str, Any], include_diagrams: bool = True,
                    diagram_b64: Optional[str] = None) -> bytes:
    """Export HLD to a PowerPoint (.pptx) presentation. Returns bytes."""
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor as PptxRGB

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    def add_slide(title_text: str, subtitle_text: str = ""):
        slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank layout

        # Dark background
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = PptxRGB(*BRAND_DARK)

        # Title
        left = Inches(0.8)
        top = Inches(0.5)
        txBox = slide.shapes.add_textbox(left, top, Inches(11.5), Inches(0.8))
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = title_text
        p.font.size = Pt(28)
        p.font.bold = True
        p.font.color.rgb = PptxRGB(*BRAND_GREEN)

        if subtitle_text:
            p2 = tf.add_paragraph()
            p2.text = subtitle_text
            p2.font.size = Pt(14)
            p2.font.color.rgb = PptxRGB(*DARK_GRAY)

        return slide

    def add_content_box(slide, text: str, left: float = 0.8, top: float = 1.5,
                        width: float = 11.5, height: float = 5.0, font_size: int = 14):
        txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        tf = txBox.text_frame
        tf.word_wrap = True

        for line in text.split("\n"):
            p = tf.add_paragraph()
            line = line.strip()
            if line.startswith("**") and line.endswith("**"):
                p.text = line.strip("*")
                p.font.bold = True
                p.font.size = Pt(font_size + 2)
                p.font.color.rgb = PptxRGB(*BRAND_GREEN)
            elif line.startswith("• ") or line.startswith("- "):
                p.text = line
                p.font.size = Pt(font_size)
                p.font.color.rgb = PptxRGB(*WHITE)
                p.level = 1
            else:
                p.text = line
                p.font.size = Pt(font_size)
                p.font.color.rgb = PptxRGB(*WHITE)
        # Remove empty first paragraph
        if tf.paragraphs and tf.paragraphs[0].text == "":
            tf.paragraphs[0]._p.getparent().remove(tf.paragraphs[0]._p)
        return txBox

    def kv_lines(pairs: List[tuple]) -> str:
        return "\n".join(f"**{k}**\n{_safe(v)}\n" for k, v in pairs if v)

    # ── Slide 1: Title ──
    title_slide = add_slide(
        hld.get("title", "High-Level Design Document"),
        "Generated by Archmorph — AI-powered Cloud Architecture Translator"
    )
    meta = hld.get("_metadata") or {}
    if meta:
        info_parts = []
        if meta.get("source_provider"):
            info_parts.append(f"Source: {meta['source_provider'].upper()}")
        if meta.get("services_count"):
            info_parts.append(f"{meta['services_count']} services")
        if meta.get("zones_count"):
            info_parts.append(f"{meta['zones_count']} zones")
        if info_parts:
            add_content_box(title_slide, " | ".join(info_parts), top=2.5, font_size=16)

    # ── Slide 2: Executive Summary ──
    s = add_slide("Executive Summary")
    add_content_box(s, _safe(hld.get("executive_summary")))

    # ── Slide 3: Architecture Overview ──
    arch = hld.get("architecture_overview") or {}
    s = add_slide("Architecture Overview")
    content = kv_lines([
        ("Architecture Style", arch.get("architecture_style")),
        ("Deployment Model", arch.get("deployment_model")),
        ("Description", arch.get("description")),
    ])
    add_content_box(s, content)

    # ── Slide: Architecture Diagram (optional) ──
    if include_diagrams and diagram_b64:
        img_bytes = _decode_diagram_image(diagram_b64)
        if img_bytes:
            s = add_slide("Architecture Diagram")
            stream = io.BytesIO(img_bytes)
            try:
                s.shapes.add_picture(stream, Inches(1.5), Inches(1.5), width=Inches(10))
            except Exception:
                add_content_box(s, "[Diagram could not be embedded]")

    # ── Slide 4: Services (split into chunks of 3) ──
    services = hld.get("services", [])
    for chunk_start in range(0, len(services), 3):
        chunk = services[chunk_start:chunk_start + 3]
        page_num = chunk_start // 3 + 1
        s = add_slide(f"Azure Services (Page {page_num})")
        lines = []
        for svc in chunk:
            lines.append(f"**{_safe(svc.get('azure_service'))}**")
            if svc.get("source_service"):
                lines.append(f"Replaces: {svc['source_service']}")
            lines.append(f"Tier: {_safe(svc.get('tier_recommendation'))} | SLA: {_safe(svc.get('sla'))} | Cost: {_safe(svc.get('estimated_monthly_cost'))}")
            lines.append(f"{_safe(svc.get('justification'), '')}")
            lines.append("")
        add_content_box(s, "\n".join(lines), font_size=12)

    # ── Slide: Networking ──
    net = hld.get("networking_design") or {}
    if net:
        s = add_slide("Networking Design")
        add_content_box(s, kv_lines([
            ("Topology", net.get("topology")),
            ("VNet Design", net.get("vnet_design")),
            ("DNS Strategy", net.get("dns_strategy")),
            ("Security Controls", ", ".join(net.get("security_controls", []))),
        ]))

    # ── Slide: Security ──
    sec = hld.get("security_design") or {}
    if sec:
        s = add_slide("Security Design")
        add_content_box(s, kv_lines([
            ("Identity & Access", sec.get("identity")),
            ("Data Protection", sec.get("data_protection")),
            ("Network Security", sec.get("network_security")),
            ("Secrets Management", sec.get("secrets_management")),
        ]))

    # ── Slide: FinOps ──
    fin = hld.get("finops") or {}
    if fin:
        s = add_slide("FinOps — Cost Management")
        content = f"**Total Estimated Monthly Cost**\n{_safe(fin.get('total_estimated_monthly_cost'))}\n\n"
        if fin.get("cost_optimization_recommendations"):
            content += "**Cost Optimization**\n"
            content += "\n".join(f"• {r}" for r in fin["cost_optimization_recommendations"])
        add_content_box(s, content)

    # ── Slide: WAF Assessment ──
    waf = hld.get("waf_assessment") or {}
    if waf:
        s = add_slide("Well-Architected Framework Assessment")
        lines = []
        for pillar in ["reliability", "security", "cost_optimization", "operational_excellence", "performance_efficiency"]:
            p = waf.get(pillar, {})
            lines.append(f"**{pillar.replace('_', ' ').title()}** — {_safe(p.get('score'))}")
            lines.append(f"{_safe(p.get('notes'), '')}")
            lines.append("")
        add_content_box(s, "\n".join(lines), font_size=13)

    # ── Slide: Migration Roadmap ──
    mig = hld.get("migration_approach") or {}
    if mig:
        s = add_slide("Migration Roadmap", f"Strategy: {_safe(mig.get('strategy'))}")
        lines = []
        for phase in mig.get("phases", []):
            lines.append(f"**Phase {phase.get('phase', '?')}: {_safe(phase.get('name'))}**")
            if phase.get("services"):
                lines.append(f"Services: {', '.join(phase['services'])}")
            lines.append(f"Duration: {phase.get('duration_weeks', '?')} weeks")
            lines.append("")
        add_content_box(s, "\n".join(lines), font_size=13)

    # ── Slide: Next Steps ──
    next_steps = hld.get("next_steps", [])
    if next_steps:
        s = add_slide("Next Steps")
        content = "\n".join(f"{i}. {step}" for i, step in enumerate(next_steps, 1))
        add_content_box(s, content)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


# ─────────────────────────────────────────────────────────────
# Public API — main dispatcher
# ─────────────────────────────────────────────────────────────
SUPPORTED_FORMATS = {"docx", "pdf", "pptx"}


def export_hld(hld: Dict[str, Any], format: str, include_diagrams: bool = True,
               diagram_b64: Optional[str] = None) -> Dict[str, Any]:
    """
    Export HLD document in the requested format.

    Returns dict with:
      - format: str
      - filename: str
      - content_b64: str (base64-encoded file bytes)
      - content_type: str (MIME type)
    """
    if format not in SUPPORTED_FORMATS:
        raise ValueError(f"Unsupported format: {format}. Use one of: {', '.join(sorted(SUPPORTED_FORMATS))}")

    title_slug = (hld.get("title", "archmorph-hld") or "archmorph-hld").lower()
    title_slug = "".join(c if c.isalnum() or c in "-_ " else "" for c in title_slug).strip().replace(" ", "-")[:50]
    if not title_slug.startswith("archmorph"):
        title_slug = f"archmorph-{title_slug}"

    exporters = {
        "docx": (export_hld_docx, f"{title_slug}.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
        "pdf":  (export_hld_pdf,  f"{title_slug}.pdf",  "application/pdf"),
        "pptx": (export_hld_pptx, f"{title_slug}.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
    }

    export_fn, filename, content_type = exporters[format]
    file_bytes = export_fn(hld, include_diagrams=include_diagrams, diagram_b64=diagram_b64)

    return {
        "format": format,
        "filename": filename,
        "content_b64": base64.b64encode(file_bytes).decode("ascii"),
        "content_type": content_type,
    }
