"""
Push generated IaC to GitHub/GitLab as a Pull Request (#504).

Creates a new branch, commits IaC files, and opens a PR with
the analysis summary and cost estimate in the description.
"""

import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

GITHUB_TOKEN_ENV = "GITHUB_TOKEN"


def push_iac_as_pr(
    *,
    repo_full_name: str,
    iac_code: str,
    iac_format: str = "terraform",
    analysis_summary: Optional[Dict[str, Any]] = None,
    cost_estimate: Optional[Dict[str, Any]] = None,
    base_branch: str = "main",
    target_path: Optional[str] = None,
    github_token: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Push generated IaC code to a GitHub repo as a Pull Request.

    Args:
        repo_full_name: "owner/repo" format
        iac_code: The generated IaC content
        iac_format: terraform, bicep, cloudformation, pulumi, aws-cdk
        analysis_summary: Optional analysis data for PR description
        cost_estimate: Optional cost data for PR description
        base_branch: Branch to merge into (default: main)
        target_path: Path in the repo for IaC files (default: infra/)
        github_token: GitHub PAT (falls back to env var)

    Returns:
        Dict with pr_url, pr_number, branch_name, or error
    """
    token = github_token or os.getenv(GITHUB_TOKEN_ENV, "")
    if not token:
        return {"success": False, "error": "GitHub token not configured. Set GITHUB_TOKEN."}

    try:
        from github import Github

        g = Github(token)
        repo = g.get_repo(repo_full_name)

        # Determine file extension and path
        ext_map = {
            "terraform": ".tf",
            "bicep": ".bicep",
            "cloudformation": ".yaml",
            "pulumi": ".ts",
            "aws-cdk": ".ts",
        }
        ext = ext_map.get(iac_format, ".tf")
        path = target_path or f"infra/main{ext}"

        # Create branch
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        branch_name = f"archmorph/iac-{iac_format}-{timestamp}"

        base_ref = repo.get_git_ref(f"heads/{base_branch}")
        repo.create_git_ref(f"refs/heads/{branch_name}", base_ref.object.sha)

        # Commit the IaC file
        commit_msg = f"feat: add {iac_format} infrastructure generated by Archmorph"
        try:
            # Update if file exists
            existing = repo.get_contents(path, ref=branch_name)
            repo.update_file(
                path=path,
                message=commit_msg,
                content=iac_code,
                sha=existing.sha,
                branch=branch_name,
            )
        except Exception:
            # Create if file doesn't exist
            repo.create_file(
                path=path,
                message=commit_msg,
                content=iac_code,
                branch=branch_name,
            )

        # Build PR description
        pr_body = _build_pr_description(iac_format, analysis_summary, cost_estimate)

        # Create PR
        pr = repo.create_pull(
            title=f"[Archmorph] Generated {iac_format.title()} Infrastructure",
            body=pr_body,
            head=branch_name,
            base=base_branch,
        )

        logger.info("Created PR #%d in %s", pr.number, repo_full_name)

        return {
            "success": True,
            "pr_number": pr.number,
            "pr_url": pr.html_url,
            "branch_name": branch_name,
            "file_path": path,
        }

    except Exception as exc:
        logger.error("Failed to push IaC as PR: %s", exc)
        return {"success": False, "error": str(exc)}


def _build_pr_description(
    iac_format: str,
    analysis: Optional[Dict[str, Any]],
    cost: Optional[Dict[str, Any]],
) -> str:
    """Build a markdown PR description with analysis and cost summaries."""
    lines = [
        "## Archmorph — Generated Infrastructure as Code",
        "",
        f"**Format:** {iac_format.title()}",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
    ]

    if analysis:
        source = analysis.get("source_provider", "unknown").upper()
        target = analysis.get("target_provider", "azure").title()
        services = analysis.get("services_detected", 0)
        mappings = analysis.get("mappings", [])
        avg_conf = analysis.get("confidence_summary", {}).get("average", 0)

        lines.extend([
            "### Migration Summary",
            f"- **Source:** {source} → **Target:** {target}",
            f"- **Services detected:** {services}",
            f"- **Service mappings:** {len(mappings)}",
            f"- **Average confidence:** {avg_conf:.0%}" if avg_conf else "",
            "",
        ])

        if mappings:
            lines.extend(["| Source | Target | Confidence |", "|--------|--------|------------|"])
            for m in mappings[:10]:  # Cap at 10
                src = m.get("source_service", "?")
                tgt = m.get("azure_service", "?")
                conf = m.get("confidence", 0)
                lines.append(f"| {src} | {tgt} | {conf:.0%} |")
            if len(mappings) > 10:
                lines.append(f"| ... | +{len(mappings) - 10} more | |")
            lines.append("")

    if cost:
        total = cost.get("total_monthly", "N/A")
        lines.extend([
            "### Cost Estimate",
            f"- **Estimated monthly cost:** ${total}" if isinstance(total, (int, float)) else f"- **Estimated monthly cost:** {total}",
            "",
        ])

    lines.extend([
        "---",
        "*Generated by [Archmorph](https://github.com/idokatz86/Archmorph) — AI-powered Cloud Architecture Translator*",
    ])

    return "\n".join(lines)
