"""
Archmorph Full Analysis Report Generator (Issue #236).

Generates a comprehensive multi-section PDF report from a completed
migration analysis session using fpdf2 (already in requirements.txt).

Sections:
  1. Cover Page
  2. Executive Summary
  3. Service Mappings Table
  4. Cost Estimate Summary
  5. Migration Risk Summary
  6. Appendix: IaC Code Preview
"""

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from version import __version__
from hld_export import _safe, _pdf_safe, BRAND_GREEN, BRAND_DARK, DARK_GRAY, LIGHT_GRAY

logger = logging.getLogger(__name__)


def generate_analysis_report_pdf(session: Dict[str, Any]) -> bytes:
    """Generate a full analysis PDF report from session data.

    Args:
        session: The analysis session dict containing mappings, iac_code,
                 cost estimates, and analysis metadata.

    Returns:
        PDF file bytes.
    """
    from fpdf import FPDF

    mappings: List[Dict[str, Any]] = session.get("mappings", [])
    cost_estimate: Optional[Dict[str, Any]] = session.get("_cached_cost_estimate")
    iac_code: Optional[str] = session.get("iac_code")
    analysis_meta = session.get("analysis", {}) or {}
    source_provider = (
        session.get("source_provider")
        or analysis_meta.get("source_provider")
        or session.get("provider")
        or "Unknown"
    )
    project_name = session.get("project_name") or session.get("title") or "Migration Analysis"

    class ReportPDF(FPDF):
        def header(self):
            if self.page_no() > 1:
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(*DARK_GRAY)
                self.cell(0, 6, _pdf_safe(f"{project_name} -- Archmorph Analysis Report"), align="L")
                self.ln(8)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(*DARK_GRAY)
            self.cell(
                0, 10,
                _pdf_safe(f"Page {self.page_no()}/{{nb}} -- Generated by Archmorph v{__version__}"),
                align="C",
            )

        def section_heading(self, text: str, level: int = 1):
            sizes = {1: 16, 2: 13, 3: 11}
            self.set_font("Helvetica", "B", sizes.get(level, 11))
            self.set_text_color(*BRAND_DARK)
            self.ln(4)
            self.multi_cell(0, 7, _pdf_safe(text))
            self.ln(2)

        def body_text(self, text: str):
            self.set_font("Helvetica", "", 10)
            self.set_text_color(51, 65, 85)
            self.multi_cell(0, 5, _pdf_safe(text))
            self.ln(1)

        def key_value(self, key: str, value: str):
            key = _pdf_safe(key)
            value = _pdf_safe(value)
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(*BRAND_DARK)
            w = self.get_string_width(f"{key}: ") + 2
            self.cell(w, 5, f"{key}: ")
            self.set_font("Helvetica", "", 10)
            self.set_text_color(51, 65, 85)
            self.multi_cell(0, 5, value)
            self.ln(1)

    pdf = ReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ──────────────────────────────────────────────────────────
    # 1. Cover Page
    # ──────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.ln(50)
    pdf.set_font("Helvetica", "B", 32)
    pdf.set_text_color(*BRAND_GREEN)
    pdf.multi_cell(0, 14, _pdf_safe(project_name), align="C")
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(*BRAND_DARK)
    pdf.cell(0, 10, "Migration Analysis Report", align="C")
    pdf.ln(14)

    pdf.set_font("Helvetica", "I", 11)
    pdf.set_text_color(*DARK_GRAY)
    pdf.cell(0, 7, f"Generated by Archmorph v{__version__}", align="C")
    pdf.ln(7)
    pdf.cell(
        0, 7,
        f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        align="C",
    )
    pdf.ln(7)
    pdf.cell(0, 7, f"Source Cloud: {source_provider.upper()}", align="C")
    pdf.ln(7)
    pdf.cell(0, 7, f"Total Services: {len(mappings)}", align="C")

    # ──────────────────────────────────────────────────────────
    # 2. Executive Summary
    # ──────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_heading("1. Executive Summary")

    pdf.key_value("Source Cloud", source_provider.upper())
    pdf.key_value("Target Cloud", "Microsoft Azure")
    pdf.key_value("Total Services Analyzed", str(len(mappings)))

    # Compute overall confidence
    confidences = [
        m.get("confidence", 0) for m in mappings
        if isinstance(m.get("confidence"), (int, float))
    ]
    avg_confidence = round(sum(confidences) / len(confidences), 1) if confidences else 0
    pdf.key_value("Average Confidence", f"{avg_confidence}%")

    # Complexity breakdown
    complexities = {}
    for m in mappings:
        c = _safe(m.get("effort") or m.get("complexity") or "medium").lower()
        complexities[c] = complexities.get(c, 0) + 1
    if complexities:
        parts = [f"{k.title()}: {v}" for k, v in sorted(complexities.items())]
        pdf.key_value("Migration Complexity", ", ".join(parts))

    # ──────────────────────────────────────────────────────────
    # 3. Service Mappings Table
    # ──────────────────────────────────────────────────────────
    pdf.section_heading("2. Service Mappings")

    if mappings:
        # Table header
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(*LIGHT_GRAY)
        pdf.set_text_color(*BRAND_DARK)
        col_source = 45
        col_azure = 45
        col_conf = 20
        col_effort = 25
        col_gaps = 50
        pdf.cell(col_source, 7, "Source Service", 1, fill=True)
        pdf.cell(col_azure, 7, "Azure Service", 1, fill=True)
        pdf.cell(col_conf, 7, "Conf. %", 1, fill=True)
        pdf.cell(col_effort, 7, "Effort", 1, fill=True)
        pdf.cell(col_gaps, 7, "Gaps / Notes", 1, fill=True)
        pdf.ln()

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(51, 65, 85)
        for m in mappings:
            source = _pdf_safe(_safe(m.get("source_service") or m.get("name"), ""))[:25]
            azure = _pdf_safe(_safe(m.get("azure_service") or m.get("target"), ""))[:25]
            conf = _pdf_safe(str(m.get("confidence", "N/A")))
            effort = _pdf_safe(_safe(m.get("effort") or m.get("complexity"), ""))[:12]
            gaps_list = m.get("gaps") or m.get("limitations") or []
            gaps = _pdf_safe(", ".join(gaps_list)[:50]) if isinstance(gaps_list, list) else ""

            pdf.cell(col_source, 6, source, 1)
            pdf.cell(col_azure, 6, azure, 1)
            pdf.cell(col_conf, 6, conf, 1)
            pdf.cell(col_effort, 6, effort, 1)
            pdf.cell(col_gaps, 6, gaps, 1)
            pdf.ln()
    else:
        pdf.body_text("No service mappings available.")

    # ──────────────────────────────────────────────────────────
    # 4. Cost Estimate Summary
    # ──────────────────────────────────────────────────────────
    pdf.section_heading("3. Cost Estimate Summary")

    if cost_estimate:
        total = cost_estimate.get("total_monthly_estimate") or cost_estimate.get("total")
        if total:
            if isinstance(total, dict):
                low = total.get("low", "N/A")
                high = total.get("high", "N/A")
                pdf.key_value("Monthly Cost Range", f"${low} - ${high}")
            else:
                pdf.key_value("Estimated Monthly Cost", f"${total}")

        categories = cost_estimate.get("by_category") or cost_estimate.get("categories") or {}
        if categories:
            pdf.body_text("Per-category breakdown:")
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_fill_color(*LIGHT_GRAY)
            pdf.cell(80, 7, "Category", 1, fill=True)
            pdf.cell(50, 7, "Monthly Cost", 1, fill=True)
            pdf.ln()

            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(51, 65, 85)
            if isinstance(categories, dict):
                for cat, val in categories.items():
                    pdf.cell(80, 6, _pdf_safe(cat), 1)
                    pdf.cell(50, 6, _pdf_safe(f"${val}" if val else "N/A"), 1)
                    pdf.ln()
            elif isinstance(categories, list):
                for item in categories:
                    pdf.cell(80, 6, _pdf_safe(_safe(item.get("category", ""))), 1)
                    pdf.cell(50, 6, _pdf_safe(f"${item.get('cost', 'N/A')}"), 1)
                    pdf.ln()

        services_cost = cost_estimate.get("services") or []
        if services_cost and isinstance(services_cost, list):
            pdf.ln(3)
            pdf.body_text("Per-service estimates:")
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_fill_color(*LIGHT_GRAY)
            pdf.cell(70, 7, "Service", 1, fill=True)
            pdf.cell(40, 7, "SKU / Tier", 1, fill=True)
            pdf.cell(40, 7, "Monthly Cost", 1, fill=True)
            pdf.ln()

            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(51, 65, 85)
            for svc in services_cost[:20]:  # Limit to top 20
                pdf.cell(70, 6, _pdf_safe(_safe(svc.get("service", "")))[:35], 1)
                pdf.cell(40, 6, _pdf_safe(_safe(svc.get("sku") or svc.get("tier", "")))[:20], 1)
                cost_val = svc.get("monthly_cost") or svc.get("cost", "N/A")
                pdf.cell(40, 6, _pdf_safe(f"${cost_val}"), 1)
                pdf.ln()
    else:
        pdf.body_text("Cost estimate not available. Generate one from the analysis page.")

    # ──────────────────────────────────────────────────────────
    # 5. Migration Risk Summary
    # ──────────────────────────────────────────────────────────
    pdf.section_heading("4. Migration Risk Summary")

    high_risk = []
    medium_risk = []
    low_risk = []
    for m in mappings:
        conf = m.get("confidence", 100)
        effort = _safe(m.get("effort") or m.get("complexity") or "medium").lower()
        name = _safe(m.get("source_service") or m.get("name"), "Unknown")
        gaps = m.get("gaps") or m.get("limitations") or []

        if (isinstance(conf, (int, float)) and conf < 60) or effort == "high" or len(gaps) > 2:
            high_risk.append(name)
        elif (isinstance(conf, (int, float)) and conf < 80) or effort == "medium":
            medium_risk.append(name)
        else:
            low_risk.append(name)

    pdf.key_value("High Risk", f"{len(high_risk)} services")
    if high_risk:
        pdf.body_text(", ".join(high_risk[:10]))
    pdf.key_value("Medium Risk", f"{len(medium_risk)} services")
    if medium_risk:
        pdf.body_text(", ".join(medium_risk[:10]))
    pdf.key_value("Low Risk", f"{len(low_risk)} services")

    pdf.ln(3)
    pdf.body_text("Recommendations:")
    recommendations = []
    if high_risk:
        recommendations.append(
            f"Prioritize proof-of-concept for high-risk services: {', '.join(high_risk[:3])}"
        )
    if any(m.get("gaps") for m in mappings):
        recommendations.append("Address identified feature gaps before migration")
    recommendations.append("Run validation tests in a staging environment before cutover")
    recommendations.append("Implement rollback procedures for each migration phase")
    for r in recommendations:
        pdf.body_text(f"  - {r}")

    # ──────────────────────────────────────────────────────────
    # 6. Appendix: IaC Code Preview
    # ──────────────────────────────────────────────────────────
    if iac_code:
        pdf.add_page()
        pdf.section_heading("Appendix: IaC Code Preview")
        pdf.body_text("First 50 lines of the generated Infrastructure as Code:")
        pdf.ln(2)

        lines = iac_code.split("\n")[:50]
        pdf.set_font("Courier", "", 7)
        pdf.set_text_color(51, 65, 85)
        for line in lines:
            pdf.multi_cell(0, 3.5, _pdf_safe(line))

        if len(iac_code.split("\n")) > 50:
            pdf.ln(3)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*DARK_GRAY)
            pdf.cell(0, 5, f"... ({len(iac_code.split(chr(10))) - 50} more lines — download full IaC for complete code)")

    return bytes(pdf.output())
